name: QA Check with Playwright

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape_and_sum:
    name: QA by 23f3001930@ds.study.iitm.ac.in
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install playwright

      - name: Run Playwright Script
        run: node sum_tables.mjs
